[[Main]]
  Name = "Home"
  Pre = "home"
  URL = "/"
  Weight = 1
[[Main]]
  Name = "Archive"
  Pre = "archive"
  URL = "post"
  Weight = 2
[[Main]]
  Name = "About"
  Pre = "user"
  URL = "about.html"
  Weight = 3